# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    # Required to run poetry install
    # See https://github.com/readthedocs/readthedocs.org/issues/4912#issuecomment-1143587902
    post_install:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --with docs

mkdocs:
  configuration: mkdocs.yml
